travis:
  secure:
    BINSTAR_TOKEN: qHmbXHlU9alkxXnSNrxTTZNmefPe6UcRTt4NZrI0NngB0ZbkKcG3zgFHX2M7oJYbwD11Th35nGG0WZ9SfSuhVfL449b2OveWAGGjst10VIqoepOo574V2Urdd7U5VGYOoB2QP6ioGGn/dLuiupMb1FP5h7jaOHkH9wFeXU/8xqnohtfvtsWH1/fZVqKZJI3mpSA2NdBofQ7RgXay4yXcFFBbv4p9pCv5Xkn/MEbJk6izi8MtZTMljSjLLzlYSacrFNr9UZ3QyB3Ew1OpykO25M1gOgTtEX/3zLGLZsM3qCVMujxSO2INzw0LYdkf59y3pPdYwA61hhliRuVxcMwW3h+pm8F2i2MwdiC2Kj+BgEfUWySVcnxkjDJ688jMox0MbvMGehmqsCq28flNiwn3QrzzcUQPpAo5Acttrdhs9UE9/6kC4rmqu5AaU8SmEZz8kkdtl94sQZxGghjyHtMAa/OKWkOhUFka0cKopa5e3IGlzyP/Swij815ILGEK2e21MCY6aByMKdD+LOFA/WgfzkRzeQWVQRIkeWHlrkvDxGJzTl4WQJlsfqt3gq5vGm3m9ks8WI+KI0C9qbJSJV1ycx15QGg8DAiAJLpt/DahM7e3qgfjtSJ7Pr7MQZcH1G0Pxcnfe11VIHkiWjYf7Ay5e093WqCRzbh94HJH4A2ddcY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
