travis:
  secure:
    BINSTAR_TOKEN: Vj4r1h0pifLIpEphrM/vv5TtShQQvOglx5SnA3UKyVqcnrKdflH80tcDyl7vss/uO7hqHlf+A7eN4ajSu+tzx/tJNZL9Sswe9/3PCq9R3oDDvZgemaD00I9MyO/V2AZm9WjjYfWIbnziE2g1KPVHKCAW18P34VBgjiHo4oNr9n9w23COq11bTSthhbB1MvCyTlsQvhOH9xv6EPF/lLnCKBZSE0zRCSZnRg4V0k8fQffwrhbTI+g6xC421+3lq+dUKZw3Pbt8o+rChSmtRUI1lhzfEdzIsn+qNCXImgybOXT+aknh0e4mPxJa+zL+9bUNmv/tEPv1zh2Cu/RQsAHaqaFEgmb/nA99heU+h+D0MjQFqHGp8/tPlkzwEHAabcZyVLnA92BDt0P7vWEO2NgDqc2o0Fizbbmm/Qx2fxmwNfCpzNKG84tcqUYuLJe0Hj1qPJmO9FM8GJ4GV319xS3mKFMg7nV/t533vWr8EHpu6E5r7BN459XUFsJ3pRwtSwmM7m755wgeeZ6hv2KvtYjIiSL4EWNVHYTrDM241r0tZzIHzaVX5T+QC/Q26UeunGfPgfPnQsQ8ENxaLniL91eeAxkdHu76IJZLh47o1OG/RQX2mS5xf0qkTfoRULxkjDlTlEzhAYxHt85+mtaEwWb6OrzWgZlEMDP6PjhVtCfKyMM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
